"""
Django settings for opsplatform project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&si&h$!m+1ov!t1+!(a@0@lfon5py-@%a6_g&x2t#+7ho8@7vu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", ]


# Application definition

INSTALLED_APPS = [
    "djangobower",
    "config",
    "accounts",
    "website",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'opsplatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opsplatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases


from config.api import Config
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'charset': 'utf8',
            #"init_command": "SET sql_mode='STRICT_TRANS_TABLES'" ,

        },
        # 'NAME': 'opsmgtv2',
        # 'USER': 'opsmgtv2',
        # 'PASSWORD': '123456',
        # 'HOST': 'localhost',
        # 'PORT': '3306',
        "NAME": Config.db()["database"],
        "USER": Config.db()["user"],
        "PASSWORD": Config.db()["password"],
        "HOST": Config.db()["host"],
        "PORT": Config.db()["port"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

AUTH_USER_MODEL = 'accounts.UserInfo'

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "bower_components"),
)


BOWER_COMPONENTS_ROOT = BASE_DIR


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
)

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
)

BOWER_INSTALLED_APPS = (
    'admin-lte#2.4.3',
    'respond',
    'html5shiv',
)

LOGGING= {
    "version" : 1,
    "disables_existing_loggers": True,
    "formatters": {
        "verbose" :   {
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'format': '%(asctime)s [%(levelname)s] %(filename)s %(funcName)s line:%(lineno)d message:%(message)s'
        },
        'main': {
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'format': '%(asctime)s [%(levelname)s] %(module)s  message:%(message)s',
        },
        'simple': {
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'format': '%(levelname)s message:%(message)s'
        },
    },
    'handlers': {
        'null': {
            'level': Config.conf()["log_level"],
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': Config.conf()["log_level"],
            'class': 'logging.StreamHandler',
            'formatter': 'main'
        },

        'file' : {
            'level': Config.conf()["log_level"],
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': Config.conf()["log_path"],
            'formatter':'verbose',
            'maxBytes': 16 * 1024 * 1024,
            'backupCount': 3,
            'encoding': 'utf-8'
        },
    },

    'loggers': {
        'django': {
            'handlers': ['null'],
            'propagate': False,
            'level':Config.conf()["log_level"],
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': Config.conf()["log_level"],
            'propagate': True,
        },

        'opsplatform': {
            'level': Config.conf()["log_level"],
            'handlers': ['file'],
            'propagate': False
        },
    },
}